
- name: Instalar pacotes basicos ubuntu 16.04
  apt: name={{ item }} state=present
  with_items: "{{ packagessamba }}"
  when: (( ansible_distribution_version == "16.04" ))
  tags:
    - apt

- name: Criar diretório sysvol
  file: path={{ sysvol }} state=directory mode=0755 owner=root group=root
  tags:
    - conf

- name: Criar diretório netlogon
  file: path={{ netlogon }} state=directory mode=0755 owner=root group=root
  tags:
    - conf

- name: Criar diretório compartilhamentos
  file: path={{ item.value }} state=directory mode=0755 owner=root group=root
  with_dict: "{{ compartilhamentos }}"
  tags:
    - conf

- name: Instalar arquivo hosts
  template: src=hosts.j2 dest=/etc/hosts mode=0644 owner=root group=root
  tags:
    - conf

- name: Instalar arquivo krb5.conf
  template: src=krb5.conf.j2 dest=/etc/krb5.conf mode=0644 owner=root group=root
  tags:
    - conf

- name: Instalar arquivo samba/smb.conf
  template: src=smb.conf.j2 dest=/etc/samba/smb.conf mode=0644 owner=root group=root
  tags:
    - conf

- name: Instalar o cron do rsync sysvol
  template: src=cronsysvolrsync.j2 dest=/etc/cron.d/cronsysvolrsync mode=0644 owner=root group=root
  tags:
    - conf

- name: Instalar o  rsync sysvol
  template: src=sysvolrsync.j2 dest=/etc/sysvolrsync mode=0755 owner=root group=root
  tags:
    - conf

- name: Copia arquivo nsswitch.conf
  copy: dest=/etc/nsswitch.conf src=nsswitch.conf mode=0644 owner=root group=root
  tags:
    - conf

- name: Ingressa no domínio
  shell: /usr/bin/samba-tool domain join {{dominio }} DC --realm={{ dominio.upper() }}  -U{{ usuario }}  -W {{ dominio }} --password="{{ password }}"
  tags:
    - addad

- name: Iniciando serviço do samba
  service: name=samba-ad-dc state=restarted
  tags:
    - addad

- name: Esperando 20 segundos
  pause: seconds=20
  tags:
    - addad

- name: Adicionado correcao de dns
  shell: samba-tool dns add {{ servidordc }}.{{ dominio }} {{ dominio }} {{ servidorlinux }}.{{ dominio }} A {{ ipservidorlinux }} -U{{ usuario }} --password {{ password }} ; cnamelinux=$(ldbsearch -H /var/lib/samba/private/sam.ldb '(invocationId=*)' --cross-ncs objectguid | grep -i -A 1 {{ servidorlinux }} | grep -i objectguid | cut -f 2 -d ":" ) ; samba-tool dns add {{ servidordc }}.{{ dominio }}  _msdcs.{{ dominio }} $cnamelinux CNAME {{ servidorlinux }}.{{ dominio }} -U{{ usuario }} --password {{ password }}
  ignore_errors: yes
  tags:
    - addad

- name: Verificar se fstab já foi alterado
  shell: grep ext4 /etc/fstab && ! grep "errors=remount-ro,acl,user_xattr,usrquota,grpquota" /etc/fstab  chdir=/etc
  register: fstabchange
  failed_when: ( fstabchange.rc not in [ 0, 1 ] )
  ignore_errors: yes
  tags:
    - fstab
    - conf

- name: Alterar /etc/fstab
  shell:  sed -i 's/errors=remount-ro/errors=remount-ro,acl,user_xattr,usrquota,grpquota/' /etc/fstab  && /bin/mount -o remount /  chdir=/etc
  when: fstabchange.rc == 0
  tags:
    - fstab
    - conf


#- name: Adicionar redirecionamento de domínio
#  blockinfile:
#    state: present
#    dest: /nomeclientutils/sambadocker/named.conf.local
#    marker: "// {mark} Redirecionamento de domínio"
#    block: |
#      zone {{ dominio }} {
#      type forward;
#      forwarders {
#      {{ ipservidordc }};
#      };
#      forward only;
#      };
#
#      zone {{ enderecoreverson }}.in-addr.arpa {
#      type forward;
#      forwarders {
#      {{ ipservidordc }};
#      };
#      forward only;
#      };

#- name: Desativar dnssec no bind9
#  lineinfile: dest=/etc/bind/named.conf.options regexp="dnssec-validation" line="\tdnssec-validation no;" state=present
#  notify:
#      - bind9
#  when: usebindredirect
