#!/bin/bash
apt-get -y install pip-python
apt-get -y install python-pip
apt-get -y install python-dev
apt-get -y install libffi-dev
apt-get -y install redis-server
apt-get -y install sshpass
apt-get install libssl-dev
pip install redis
pip install ansible
pip install yolk
pip install docker-py
#yolk -V ansible
#pip install --force-reinstall --upgrade ansible==2.0.2.0
