#!/bin/bash


function add(){
    cat $1 >> $2
}

function remove(){

tempmark1=$(cat $1 | head -n 1)
tempmark2=$(cat $1 | tail -n 1)


sed -i "/$tempmark1/,/$tempmark2/d" $2

}


eval ${1} ${2} ${3}
