#!/bin/bash

function servidor(){
echo -e "
define host{
        use                     generic-host
        host_name               $1
        alias                   $1
        address                 $2
        }
define service{
        use                             generic-service
        host_name                       $1
        service_description             Status Dalraf
        check_command                   check-status-base
        }
"

}

function atm(){
echo -e "
define host{
        use                     generic-host
        host_name               $1
        alias                   $1
        address                 $2
        }
define service{
        use                             generic-service
        host_name                       $1
        service_description             PING
        check_command                   check-host-base
        }
"
}


eval ${1} ${2} ${3}

