#!/bin/bash
echo -e "[basicubuntu]\n$1 ansible_user=nomeclient ansible_port=22 ansible_ssh_pass=123456 ansible_become=yes ansible_become_user=root ansible_become_method=sudo ansible_become_pass=123456" > /tmp/basicubuntuhosts 
ansible-playbook  -i /tmp/basicubuntuhosts /nomeclient/ansible/site.yml



