#!/bin/bash
[ -z "$*" ] && echo "removeremail host email password usuario" && exit 0
ansible-playbook  -i /nomeclient/ansible/hosts /nomeclient/ansible/utils/removeremail.yml -e hostemail=${1} -e email=${2} -e password=${3} -e usuario=${4}
